package com.common;

public enum PageType {
	CUSTOMER_MANAGEMENT_PAGE,
	HOME_PAGE,
	BOOKING_PAGE,
	BOOKING_DETAIL_PAGE,
	EMPLOYEE_MANAGEMENT_PAGE,
	ROOM_MANAGEMENT_PAGE,
	ROOM_TYPE_MANAGEMENT_PAGE,
	REPORT_MANAGEMENT_PAGE,
	STATISTIC_PAGE,
	LOGIN_PAGE,
	PROFILE_PAGE,
	HOTELINFO_PAGE

}
